#!/usr/bin/env php
<?php

define('ARTISAN_BINARY', 'artisan');

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
}

$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new \Symfony\Component\Console\Input\ArgvInput);

exit($status);
